# 引入常用的package

In [1]:
import pandas as pd
from sklearn import preprocessing
import numpy as np

In [2]:
train_data = pd.read_csv("sf_data/train.csv")
test_data = pd.read_csv('sf_data/test.csv')

## 1 理解数据
    任何算法的第一步，一定是深入理解所得的数据，懂业务更佳。

1. Dates - 时间标签
2. **Category** - 犯罪类型 我们的目标标签
3. Descript - 具体犯罪描述 (only in train.csv)
4. DayOfWeek - 本周的第几天
5. PdDistrict -  警局辖区名称
6. Resolution - 解决方式 (only in train.csv)
7. Address - 发生地址 
8. X - Longitude
9. Y - Latitude

In [3]:
train_data.head(2)

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y
0,2015-05-13 23:53:00,WARRANTS,WARRANT ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
1,2015-05-13 23:53:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599

In [4]:
test_data.head(2)

,Id,Dates,DayOfWeek,PdDistrict,Address,X,Y
0,0,2015-05-10 23:59:00,Sunday,BAYVIEW,2000 Block of THOMAS AV,-122.399588,37.735051
1,1,2015-05-10 23:51:00,Sunday,BAYVIEW,3RD ST / REVERE AV,-122.391523,37.732432

In [5]:
sample_data = test_data.sample(100) # 随机取100个样本

In [7]:
sample_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 682123 to 541363
Data columns (total 7 columns):
Id            100 non-null int64
Dates         100 non-null object
DayOfWeek     100 non-null object
PdDistrict    100 non-null object
Address       100 non-null object
X             100 non-null float64
Y             100 non-null float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.2+ KB

In [8]:
sample_data.describe()

                  Id           X           Y
count     100.000000  100.000000  100.000000
mean   471011.650000 -122.423016   37.765097
std    244643.991672    0.025020    0.025241
min       566.000000 -122.496803   37.708475
25%    258500.750000 -122.429721   37.751541
50%    511690.500000 -122.416509   37.775421
75%    679522.750000 -122.407634   37.784189
max    872944.000000 -122.385415   37.804734

### 数据预处理
##### 标准化 模块提供了一个实用类 StandardScaler

In [9]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler() # 引入标准化类

scaler.fit(sample_data[['X','Y']])

scaler.mean_ # 标准化前的均值

scaler.scale_# 标准化前的标准差

scaler.var_ # 标准化前的方差

standard_data = pd.DataFrame(scaler.transform(sample_data[['X','Y']]),columns=['X','Y'])

standard_data.head(3)

# standard_data.head()

standard_data.mean(axis=0) # 归一化后的数据均值

standard_data.std() #归一化后的数据方差

scaler.inverse_transform(standard_data[['X','Y']]) # 恢复数据操作

In [23]:
pd.concat([standard_data,standard_data],axis=1)

           X         Y         X         Y
0  -1.447504 -1.459812 -1.447504 -1.459812
1   0.887749  0.810724  0.887749  0.810724
2   0.433501  0.675958  0.433501  0.675958
3   0.602730  0.165154  0.602730  0.165154
4   0.113202 -0.257951  0.113202 -0.257951
5   0.134869 -0.034887  0.134869 -0.034887
6   0.617907  0.760229  0.617907  0.760229
7   0.733474  0.850405  0.733474  0.850405
8  -0.488946 -0.096616 -0.488946 -0.096616
9   0.259427 -0.412045  0.259427 -0.412045
10 -0.094105 -2.172975 -0.094105 -2.172975
11  0.056937 -0.519584  0.056937 -0.519584
12 -2.398813  0.714300 -2.398813  0.714300
13  0.065420  1.138962  0.065420  1.138962
14 -2.117253 -1.800951 -2.117253 -1.800951
15  1.029439  0.695127  1.029439  0.695127
16  0.071213 -0.981792  0.071213 -0.981792
17  0.787775  0.411080  0.787775  0.411080
18 -0.012597  0.857277 -0.012597  0.857277
19 -0.882893  0.491474 -0.882893  0.491474
20  1.068277  1.156633  1.068277  1.156633
21  0.372060  0.741941  0.372060  0.741941
22 -0.080043  1.032615 -0.080043  1.032615
23 -2.890904 -0.949697 -2.890904 -0.949697
24  0.057450  1.191732  0.057450  1.191732
25 -1.222994 -2.254547 -1.222994 -2.254547
26  0.159198 -0.257396  0.159198 -0.257396
27  0.572228  0.598821  0.572228  0.598821
28  0.301579  0.659288  0.301579  0.659288
29 -0.637382  0.690884 -0.637382  0.690884
..       ...       ...       ...       ...
70  0.622505  0.470929  0.622505  0.470929
71  0.661869 -0.342846  0.661869 -0.342846
72  0.160586 -0.513316  0.160586 -0.513316
73  0.443002  0.793410  0.443002  0.793410
74  0.045766 -0.040130  0.045766 -0.040130
75  1.436811 -1.761049  1.436811 -1.761049
76 -0.355481 -1.306480 -0.355481 -1.306480
77  0.667345  0.310542  0.667345  0.310542
78 -0.022692 -1.003882 -0.022692 -1.003882
79 -1.975143  0.845538 -1.975143  0.845538
80  0.787775  0.411080  0.787775  0.411080
81  1.372281 -0.030813  1.372281 -0.030813
82  0.140412 -0.034554  0.140412 -0.034554
83  0.319309  0.735309  0.319309  0.735309
84 -0.853548 -2.104496 -0.853548 -2.104496
85 -2.324382 -0.069894 -2.324382 -0.069894
86 -0.266280  0.285398 -0.266280  0.285398
87  0.583281  0.770677  0.583281  0.770677
88  0.368347 -0.370676  0.368347 -0.370676
89 -0.303357 -1.732611 -0.303357 -1.732611
90  0.263356  0.833005  0.263356  0.833005
91 -2.758467  0.320505 -2.758467  0.320505
92 -0.672778 -1.713262 -0.672778 -1.713262
93  0.359904  0.704634  0.359904  0.704634
94 -2.815884  0.855406 -2.815884  0.855406
95  0.286442  0.733420  0.286442  0.733420
96 -1.025883  0.071102 -1.025883  0.071102
97 -0.278584  0.833675 -0.278584  0.833675
98 -1.577130  0.751013 -1.577130  0.751013
99 -0.367972  0.035261 -0.367972  0.035261

[100 rows x 4 columns]

In [24]:
##### 另一个实用类 MinMaxScaler

minmax = preprocessing.MinMaxScaler() # 引入归一化类

minmax.fit(sample_data[['X','Y']])

minmax_data = pd.DataFrame(minmax.transform(sample_data[['X','Y']]),columns=['X','Y'])

minmax_data.head()

minmax = preprocessing.MinMaxScaler(feature_range=(4,5)) # 引入归一化类

minmax.fit_transform(sample_data[['X','Y']])[0:3]

          X         Y
0  0.338930  0.207350
1  0.860838  0.799744
2  0.759318  0.764583
3  0.797139  0.631312
4  0.687734  0.520922

##### 分类特征处理

In [29]:
sample_data.head(4)

sample_data['DayOfWeek'].unique()

le = preprocessing.LabelEncoder() # 引入LabelEncoder

le.fit(sample_data['DayOfWeek'])

le.transform(sample_data['DayOfWeek'])[0:4] # 转为默认的列向量

le.classes_

sample_data.head()

sample_data['DayOfWeek'].unique()

sample_data['Address'].unique()

sample_data['PdDistrict'].unique()

,Id,Dates,DayOfWeek,PdDistrict,Address,X,Y
682123,682123,2005-09-16 19:00:00,Friday,INGLESIDE,100 Block of WESTWOOD DR,-122.459050,37.728435
273725,273725,2011-08-19 14:00:00,Friday,SOUTHERN,100 Block of 3RD ST,-122.400916,37.785457
793775,793775,2004-03-11 21:20:00,Thursday,TENDERLOIN,GOLDEN GATE AV / JONES ST,-122.412224,37.782073
779612,779612,2004-05-19 20:37:00,Wednesday,SOUTHERN,DIVISION ST / POTRERO AV,-122.408011,37.769244

In [34]:
### 有时候one-hot更合理，接下来引入one-hot变量 

enc = preprocessing.OneHotEncoder() # 引入onehot编码类

enc.fit(sample_data[['DayOfWeek','PdDistrict']])

sample_data['PdDistrict'].unique()

enc_array = enc.transform(sample_data[['DayOfWeek','PdDistrict']]).toarray()

enc_array.shape

sample_data.head(2)

enc.inverse_transform(enc_array)[0:4] #还原编码前特征

enc.get_feature_names()

enc_array.shape

enc.get_feature_names()

enc_array[0]

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

#### 空值的填充

In [49]:
sample_data.info()

from sklearn.utils import shuffle
sample_data = sample_data.reset_index()
sample_data.loc[0:10,'X']=np.nan
sample_data.loc[20:30,'DayOfWeek']=np.nan
sample_data = shuffle(sample_data)
sample_data  = sample_data.reset_index()

sample_data

sample_data.info()

from sklearn.impute import SimpleImputer

strategy : string, optional (default=”mean”)
The imputation strategy. ['mean','median','most_frequent','constant']

# 针对数值型
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

imp.fit(sample_data[['X']])

sample_data['X_fill']=imp.transform(sample_data[['X']])

imp.statistics_

imp_freq = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

imp_freq.fit(sample_data[['DayOfWeek']])

sample_data['DayOfWeek_fill']=imp_freq.transform(sample_data[['DayOfWeek']])

imp_freq.statistics_

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 682123 to 541363
Data columns (total 7 columns):
Id            100 non-null int64
Dates         100 non-null object
DayOfWeek     100 non-null object
PdDistrict    100 non-null object
Address       100 non-null object
X             100 non-null float64
Y             100 non-null float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.2+ KB

#### 多项式特征

interaction_only =False

#### X 的特征从 (X_1, X_2) 转换为 (1, X_1, X_2, X_1^2, X_1X_2, X_2^2) 。

interaction_only = True

#### X 的特征从 (X_1, X_2) 转换为 (1, X_1, X_2, X_1X_2) 。

In [60]:
from sklearn.preprocessing import PolynomialFeatures

In [63]:
poly = PolynomialFeatures(degree=2, interaction_only=True)

In [64]:
poly.fit(sample_data[['X_fill','Y']])

PolynomialFeatures(degree=2, include_bias=True, interaction_only=True)

In [65]:
poly.transform(sample_data[['X_fill','Y']])

array([[ 1.00000000e+00, -1.22430568e+02,  3.77215834e+01,
        -4.61827487e+03],
       [ 1.00000000e+00, -1.22388799e+02,  3.77375756e+01,
        -4.61865655e+03],
       [ 1.00000000e+00, -1.22475647e+02,  3.77285281e+01,
        -4.62082590e+03],
       [ 1.00000000e+00, -1.22423506e+02,  3.77864541e+01,
        -4.62595018e+03],
       [ 1.00000000e+00, -1.22482732e+02,  3.77830359e+01,
        -4.62776946e+03],
       [ 1.00000000e+00, -1.22429645e+02,  3.77722643e+01,
        -4.62444489e+03],
       [ 1.00000000e+00, -1.22496803e+02,  3.77757940e+01,
        -4.62741399e+03],
       [ 1.00000000e+00, -1.22494982e+02,  3.77412458e+01,
        -4.62311324e+03],
       [ 1.00000000e+00, -1.22423506e+02,  3.77547485e+01,
        -4.62206868e+03],
       [ 1.00000000e+00, -1.22408068e+02,  3.77839917e+01,
        -4.62506544e+03],
       [ 1.00000000e+00, -1.22408163e+02,  3.77805345e+01,
        -4.62464583e+03],
       [ 1.00000000e+00, -1.22432176e+02,  3.77659823e+01,
        -4.62377139e+03],
       [ 1.00000000e+00, -1.22412602e+02,  3.78047338e+01,
        -4.62777585e+03],
       [ 1.00000000e+00, -1.22423329e+02,  3.77866266e+01,
        -4.62596464e+03],
       [ 1.00000000e+00, -1.22421586e+02,  3.77950262e+01,
        -4.62692704e+03],
       [ 1.00000000e+00, -1.22413754e+02,  3.77837300e+01,
        -4.62524822e+03],
       [ 1.00000000e+00, -1.22415695e+02,  3.77825852e+01,
        -4.62518142e+03],
       [ 1.00000000e+00, -1.22444995e+02,  3.77774398e+01,
        -4.62565841e+03],
       [ 1.00000000e+00, -1.22409797e+02,  3.77864221e+01,
        -4.62542827e+03],
       [ 1.00000000e+00, -1.22403405e+02,  3.77754207e+01,
        -4.62384011e+03],
       [ 1.00000000e+00, -1.22421876e+02,  3.77640889e+01,
        -4.62315063e+03],
       [ 1.00000000e+00, -1.22448554e+02,  3.77668824e+01,
        -4.62450015e+03],
       [ 1.00000000e+00, -1.22403405e+02,  3.77754207e+01,
        -4.62384011e+03],
       [ 1.00000000e+00, -1.22413846e+02,  3.77557875e+01,
        -4.62183116e+03],
       [ 1.00000000e+00, -1.22412423e+02,  3.77648250e+01,
        -4.62288373e+03],
       [ 1.00000000e+00, -1.22406000e+02,  3.77885406e+01,
        -4.62554411e+03],
       [ 1.00000000e+00, -1.22423506e+02,  3.77854575e+01,
        -4.62582818e+03],
       [ 1.00000000e+00, -1.22396422e+02,  3.77941447e+01,
        -4.62586809e+03],
       [ 1.00000000e+00, -1.22415508e+02,  3.78024597e+01,
        -4.62760730e+03],
       [ 1.00000000e+00, -1.22423506e+02,  3.77642206e+01,
        -4.62322828e+03],
       [ 1.00000000e+00, -1.22445358e+02,  3.77148371e+01,
        -4.61800671e+03],
       [ 1.00000000e+00, -1.22423506e+02,  3.77586185e+01,
        -4.62254245e+03],
       [ 1.00000000e+00, -1.22394679e+02,  3.77847691e+01,
        -4.62465468e+03],
       [ 1.00000000e+00, -1.22419018e+02,  3.77522052e+01,
        -4.62158789e+03],
       [ 1.00000000e+00, -1.22438883e+02,  3.77824478e+01,
        -4.62604070e+03],
       [ 1.00000000e+00, -1.22397073e+02,  3.77173249e+01,
        -4.61649015e+03],
       [ 1.00000000e+00, -1.22403919e+02,  3.77871161e+01,
        -4.62529110e+03],
       [ 1.00000000e+00, -1.22397389e+02,  3.77825543e+01,
        -4.62448599e+03],
       [ 1.00000000e+00, -1.22423506e+02,  3.77841894e+01,
        -4.62567293e+03],
       [ 1.00000000e+00, -1.22423506e+02,  3.77626703e+01,
        -4.62303849e+03],
       [ 1.00000000e+00, -1.22462277e+02,  3.77839579e+01,
        -4.62710952e+03],
       [ 1.00000000e+00, -1.22410253e+02,  3.77141402e+01,
        -4.61659745e+03],
       [ 1.00000000e+00, -1.22425008e+02,  3.77910301e+01,
        -4.62656718e+03],
       [ 1.00000000e+00, -1.22423506e+02,  3.77820729e+01,
        -4.62541383e+03],
       [ 1.00000000e+00, -1.22444264e+02,  3.77122438e+01,
        -4.61764794e+03],
       [ 1.00000000e+00, -1.22411988e+02,  3.77850227e+01,
        -4.62533973e+03],
       [ 1.00000000e+00, -1.22388854e+02,  3.77643229e+01,
        -4.62193220e+03],
       [ 1.00000000e+00, -1.22415722e+02,  3.77830680e+01,
        -4.62524154e+03],
       [ 1.00000000e+00, -1.22480879e+02,  3.77633414e+01,
        -4.62528726e+03],
       [ 1.00000000e+00, -1.22408771e+02,  3.77801357e+01,
        -4.62461997e+03],
       [ 1.00000000e+00, -1.22439764e+02,  3.77220694e+01,
        -4.61868128e+03],
       [ 1.00000000e+00, -1.22385415e+02,  3.77425517e+01,
        -4.61913786e+03],
       [ 1.00000000e+00, -1.22475723e+02,  3.77198671e+01,
        -4.61976800e+03],
       [ 1.00000000e+00, -1.22421387e+02,  3.77937009e+01,
        -4.62675730e+03],
       [ 1.00000000e+00, -1.22424623e+02,  3.77766740e+01,
        -4.62479509e+03],
       [ 1.00000000e+00, -1.22493115e+02,  3.77865797e+01,
        -4.62859584e+03],
       [ 1.00000000e+00, -1.22491686e+02,  3.77731460e+01,
        -4.62689632e+03],
       [ 1.00000000e+00, -1.22458981e+02,  3.77153417e+01,
        -4.61858233e+03],
       [ 1.00000000e+00, -1.22431865e+02,  3.77322854e+01,
        -4.61963408e+03],
       [ 1.00000000e+00, -1.22415067e+02,  3.77835635e+01,
        -4.62527745e+03],
       [ 1.00000000e+00, -1.22443273e+02,  3.77230856e+01,
        -4.61893807e+03],
       [ 1.00000000e+00, -1.22420787e+02,  3.77690595e+01,
        -4.62371799e+03],
       [ 1.00000000e+00, -1.22421598e+02,  3.77520477e+01,
        -4.62166603e+03],
       [ 1.00000000e+00, -1.22407519e+02,  3.77769238e+01,
        -4.62417952e+03],
       [ 1.00000000e+00, -1.22408221e+02,  3.77257475e+01,
        -4.61794166e+03],
       [ 1.00000000e+00, -1.22423506e+02,  3.77105240e+01,
        -4.61665456e+03],
       [ 1.00000000e+00, -1.22429951e+02,  3.77860339e+01,
        -4.62614227e+03],
       [ 1.00000000e+00, -1.22415885e+02,  3.77835161e+01,
        -4.62530256e+03],
       [ 1.00000000e+00, -1.22403941e+02,  3.77843007e+01,
        -4.62494730e+03],
       [ 1.00000000e+00, -1.22423506e+02,  3.77692444e+01,
        -4.62384332e+03],
       [ 1.00000000e+00, -1.22404715e+02,  3.77301608e+01,
        -4.61834959e+03],
       [ 1.00000000e+00, -1.22415508e+02,  3.77816543e+01,
        -4.62506041e+03],
       [ 1.00000000e+00, -1.22416452e+02,  3.77863087e+01,
        -4.62566585e+03],
       [ 1.00000000e+00, -1.22416460e+02,  3.77860171e+01,
        -4.62563044e+03],
       [ 1.00000000e+00, -1.22421243e+02,  3.77404397e+01,
        -4.62023154e+03],
       [ 1.00000000e+00, -1.22420254e+02,  3.77536816e+01,
        -4.62181528e+03],
       [ 1.00000000e+00, -1.22406539e+02,  3.77564864e+01,
        -4.62164083e+03],
       [ 1.00000000e+00, -1.22425779e+02,  3.77823192e+01,
        -4.62552986e+03],
       [ 1.00000000e+00, -1.22402583e+02,  3.77998450e+01,
        -4.62679864e+03],
       [ 1.00000000e+00, -1.22406403e+02,  3.77728958e+01,
        -4.62364430e+03],
       [ 1.00000000e+00, -1.22417641e+02,  3.77871735e+01,
        -4.62581666e+03],
       [ 1.00000000e+00, -1.22419520e+02,  3.77642289e+01,
        -4.62307879e+03],
       [ 1.00000000e+00, -1.22419658e+02,  3.77642206e+01,
        -4.62308298e+03],
       [ 1.00000000e+00, -1.22403405e+02,  3.77754207e+01,
        -4.62384011e+03],
       [ 1.00000000e+00, -1.22387248e+02,  3.77208692e+01,
        -4.61655336e+03],
       [ 1.00000000e+00, -1.22399768e+02,  3.77288813e+01,
        -4.61800633e+03],
       [ 1.00000000e+00, -1.22412054e+02,  3.77816136e+01,
        -4.62492493e+03],
       [ 1.00000000e+00, -1.22472185e+02,  3.77863318e+01,
        -4.62777463e+03],
       [ 1.00000000e+00, -1.22426384e+02,  3.77646439e+01,
        -4.62338882e+03],
       [ 1.00000000e+00, -1.22392382e+02,  3.77500208e+01,
        -4.62031498e+03],
       [ 1.00000000e+00, -1.22408495e+02,  3.77844517e+01,
        -4.62513789e+03],
       [ 1.00000000e+00, -1.22407634e+02,  3.77841894e+01,
        -4.62507320e+03],
       [ 1.00000000e+00, -1.22423506e+02,  3.77284346e+01,
        -4.61884724e+03],
       [ 1.00000000e+00, -1.22453461e+02,  3.77084754e+01,
        -4.61753333e+03],
       [ 1.00000000e+00, -1.22394146e+02,  3.77825833e+01,
        -4.62436701e+03],
       [ 1.00000000e+00, -1.22419858e+02,  3.77861371e+01,
        -4.62577355e+03],
       [ 1.00000000e+00, -1.22423581e+02,  3.77398850e+01,
        -4.62025185e+03],
       [ 1.00000000e+00, -1.22414056e+02,  3.77827931e+01,
        -4.62514496e+03],
       [ 1.00000000e+00, -1.22419053e+02,  3.77586324e+01,
        -4.62237601e+03],
       [ 1.00000000e+00, -1.22421644e+02,  3.77429970e+01,
        -4.62055976e+03]])